<?php
// Error reporting
error_reporting(E_ALL^E_NOTICE);

// Including the DB connection file
require('./includes/db.php');

$directory = './media/files';

// open the current directory
$dir = @opendir($directory) or die("There is an error with your file directory!");

// define an array to hold the files
$files = array();

$extension = '';

// loop through all of the files
while ($file = readdir($dir)) {
	
  // Skipping the system files
  if ($file{0} == '.') continue;
  
  // end() returns the last element of the array generated by the explode() function
  $extension = strtolower(end(explode('.',$file)));
  
  if ($file == 'php') continue;
		  
  // store the filename
  $files[] = $file;
}

// Now loop through the files
rsort($files);

// Select filenames from database
$file_downloads = array();

$result = mysqli_query($db, 'SELECT * FROM dl_manager');

if(mysqli_num_rows($result)) {
	while($row = mysqli_fetch_assoc($result)) {
		/* The key of the $file_downloads array will be the name of the file and will contain the number of downloads */
		$file_downloads[$row['filename']] = $row['downloads'];
	}
}

// Display the list of files
foreach($files as $filename)
{
	// Builds the table list
	$details = explode('_', $filename);	
	
	$sermon = $details[2];
	$sermontitle = str_replace('-', ' ', $sermon);
	$trim = trim($sermontitle, '.mp3');
	
	$speaker = $details[1];
	$speakertrim = str_replace('-', ' ', $speaker);
	
	$date = $details[0];

	echo('<tr><td class="sermontitle"><a href="media/download.php?file=' . $filename . '" rel="0" class="newWindow">' . '"' . $trim . '"
	<span class="download-count" title="Times Downloaded">' . (int)$file_downloads[$filename] . '</span></a></td><td class="speaker tdata">' . $speakertrim . '</td>' . '<td class="date tdata">' . $date . '</td></tr>');
}
?>