<?php
// Error reporting
error_reporting(E_ALL^E_NOTICE);

// Including the DB connection file
require('./includes/db.php');

$directory = './media/files';

// open the current directory
$dir = @opendir($directory) or die("There is an error with your file directory!");

// define an array to hold the files
$files = array();

$extension = '';

// loop through all of the files
while ($file = readdir($dir)) {
	
  // Skipping the system files
  if ($file{0} == '.') continue;
  
  // end() returns the last element of the array generated by the explode() function
  $var = explode('.',$file);
  $extension = strtolower(end($var));
  
  if ($file == 'php') continue;
		  
  // store the filename
  $files[] = $file;
}

// Now loop through the files
rsort($files);

// Select filenames from database
$file_downloads = array();

$result = mysqli_query($db, 'SELECT * FROM dl_manager');

if(mysqli_num_rows($result)) {
	while($row = mysqli_fetch_assoc($result)) {
		/* The key of the $file_downloads array will be the name of the file and will contain the number of downloads */
		$file_downloads[$row['filename']] = $row['downloads'];
		$file_expiration[$row['filename']] = $row['expiration_date'];
	}
}

// Display the list of files
foreach($files as $filename)
{
	// Builds the table list
	$details = explode('_', $filename);	 // an array of the parts of the MP3 filename
										 //  which are date, speaker, then title

	$sermon = $details[2];
	$sermontitle = str_replace('-', ' ', $sermon);
	$trim = trim($sermontitle, '.mp3');
	
	/** When naming files that contain verses, use ! in place of : **/
	/** and @ in place of - (exclamation mark in place of colon, at in place of dash. **/
	/** # replaces ' (apostrophe)
	/** * replaces ? (question mark)
	/** The next two lines replace those characters **/
	$trim = str_replace('!', ':', $trim);
	$trim = str_replace('@', '-', $trim);
	$trim = str_replace("#", "'", $trim);
	$trim = str_replace('*', '?', $trim);
	
	$speaker = $details[1];
	$speakertrim = str_replace('-', ' ', $speaker);
	
	$date = explode('-', $details[0]);
	
	$date[0] = '20' . $date[0];
		
	// $date[0] is the year
	// $date[1] is the month
	// $date[2] is the day
	
	switch($date[1]) {
		case '01' :
			$date[1] = 'January';
			break;
		case '02' :
			$date[1] = 'February';
			break;
		case '03' :
			$date[1] = 'March';
			break;
		case '04' :
			$date[1] = 'April';
			break;
		case '05' :
			$date[1] = 'May';
			break;
		case '06' :
			$date[1] = 'June';
			break;
		case '07' :
			$date[1] = 'July';
			break;
		case '08' :
			$date[1] = 'August';
			break;
		case '09' :
			$date[1] = 'September';
			break;
		case '10' :
			$date[1] = 'October';
			break;
		case '11' :
			$date[1] = 'November';
			break;
		case '12' :
			$date[1] = 'December';
			break;
		default :
			$date[1] = 'no date';
			break;
	}
	
		
	// Query database for expiration date - if expired, do not list	
	if($file_expiration[$filename] === NULL || $file_expiration[$filename] === ''){
		$file_expiration[$filename] = '2030-12-31';
	}
	if(time() >= strtotime($file_expiration[$filename])){
		continue;
	}
?>
	<tr>
		<td class="stitle">
			<a href="media/download.php?file=<?php echo $filename ?>" rel="0" class="newWindow"><?php echo $trim ?>
			</a>
		</td>
		<td class="speaker tdata"><?php echo $speakertrim ?></td>
		<td class="date tdata"><?php echo $date[1].' '.$date[2].', '.$date[0] ?>
				<td><span class="download-count" title="Times Downloaded"><?php echo (int)$file_downloads[$filename]?>
				</span></td>
		</td>
	</tr>
<?php } ?>